#For Login/Logout
SelectorId_LoginUserName = "login_username"
SelectorName_Username = "username"
SelectorClass_NextButton = "button-fill"
SelectorClass_SubmitButton = "submit-login"
SelectorClass_LoginPassword = "password"
SelectorClass_ChatIcon = "icon-chat"
SelectorClass_ChatTitle = "sliding"
SelectorId_SidebarExpand = "main-menu-drag-handle"
SelectorId_AdministrationMenu = "main-menu-administration"
SelectorClass_LogoutButton = "logout-button"
SelectorClass_SideBarChatIcon = "menu-label"
Email_Add = "eagalleto@gmail.com"
Password = "Tommy123"

#For AddContact_NewChat
SelectorClass_AddNewMenu = "open-popover"
SelectorClass_AddNewMenu_NewChat = "popover-inner"
SelectorClass_AddNewMenu_NewChatCheckBox = "label-checkbox"
SelectorClass_AddNewMenu_NewChatOkButton = "done-select-contact"
SelectorId_AddNewMenu_TextBox = "message-box"
SelectorClass_AddNewMenu_TextBoxSendBUtton = "messagebar"
SelectorClass_AssertInputtedText = "messages-auto-layout"
SelectorClass_ModalContacts = "modal-in"
SelectorClass_OverLay = "modal-overlay-visible"
SelectorClass_CheckBox = "item-media"
SelectorClass_InputtedText = "message-text"