version: 2
jobs:
  build:
    docker:
      - image: circleci/python:jessie-node-browsers
    steps:
      - checkout
      - run: 
          name: Install BrowserStack 
          command: npm install browserstack 
      - run: 
          name: sauce testing
          command: python Tommy_SmokeTest.py
          environment:
            SAUCE_USERNAME: masonfok1
            SAUCE_ACCESS_KEY: yYkqqhe5936SdqbzsUxo
      - run: # Wait for app to be ready
          command: wget --retry-connrefused --no-check-certificate -T 30 http://localhost:5000
      - run: # Run selenium tests
          command: nosetests
      - run: # wait for Sauce Connect to close the tunnel
          command: killall --wait sc  