version: 2
jobs:
  build:
    docker:
      - image: circleci/python:jessie-node-browsers
    steps:
      - checkout
      - run: 
          name: Install BrowserStack 
          command: npm install browserstack 
      - run: 
          name: sauce testing
          command: npm run-script sauce
          environment:
            SAUCE_USERNAME: # Refer to circleci.com/docs/2.0/env-vars documentation for info
            SAUCE_ACCESS_KEY: # about setting up environment variables for auth secrets
      - run: # Wait for app to be ready
          command: wget --retry-connrefused --no-check-certificate -T 30 http://localhost:5000
      - run: # Run selenium tests
          command: nosetests
      - run: # wait for Sauce Connect to close the tunnel
          command: killall --wait sc  